// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/.DS_Store",
    "/app-ads.txt",
    "/faq/ar.htm",
    "/faq/bn.htm",
    "/faq/de.htm",
    "/faq/el.htm",
    "/faq/en.htm",
    "/faq/es.htm",
    "/faq/fr.htm",
    "/faq/it.htm",
    "/faq/ja.htm",
    "/faq/ko.htm",
    "/faq/nl.htm",
    "/faq/pl.htm",
    "/faq/pt.htm",
    "/faq/ru.htm",
    "/faq/th.htm",
    "/faq/uk.htm",
    "/faq/vi.htm",
    "/faq/zh-CN.htm",
    "/faq/zh-TW.htm",
    "/favicon.png",
    "/fonts/Quicksand.ttf",
    "/img/3-No-verification.svg",
    "/img/DAO.svg",
    "/img/ICPicon.svg",
    "/img/ICicon.svg",
    "/img/NoMnemonicWords.svg",
    "/img/NoPassword.svg",
    "/img/NoPrivateKey.svg",
    "/img/Web3.svg",
    "/img/android_apk.png",
    "/img/appMain.png",
    "/img/appMain1.png",
    "/img/apple_store.svg",
    "/img/block.png",
    "/img/container.png",
    "/img/decentralization.svg",
    "/img/delta.logo.png",
    "/img/delta.logo.svg",
    "/img/delta_new_screen_1.png",
    "/img/delta_new_screen_2.png",
    "/img/dsms_verifier_terminal.jpg",
    "/img/dsms_verifier_terminal.png",
    "/img/environmentallyFriendly.svg",
    "/img/fairness.svg",
    "/img/footer-bg.svg",
    "/img/google_play.svg",
    "/img/handheld.delta.app.png",
    "/img/handheld.delta.app.psd",
    "/img/handheld.delta.app1.png",
    "/img/handheld.delta.png",
    "/img/icp-logo.svg",
    "/img/launch.png",
    "/img/map-image.jpg",
    "/img/map-world.png",
    "/img/map-world2.png",
    "/img/medium.png",
    "/img/mobilePriority.svg",
    "/img/multiChainWallet.svg",
    "/img/nectar-shape-divider.svg",
    "/img/no_passwords_new.png",
    "/img/no_private_keys_new.png",
    "/img/no_recovery_phrases_new.png",
    "/img/progress_arrow.png",
    "/img/progress_arrow1.png",
    "/img/safetyCircle.svg",
    "/img/whitepaper1.png",
    "/img/whitepaper2.png",
    "/img/whitepaper3.png",
    "/img/whitepaper4.png",
    "/img/xiaomi_GetApps.png",
    "/robots.txt",
    "/whitepaper/bn.htm",
    "/whitepaper/de.htm",
    "/whitepaper/el.htm",
    "/whitepaper/en.htm",
    "/whitepaper/es.htm",
    "/whitepaper/fr.htm",
    "/whitepaper/it.htm",
    "/whitepaper/ja.htm",
    "/whitepaper/ko.htm",
    "/whitepaper/nl.htm",
    "/whitepaper/pl.htm",
    "/whitepaper/pt.htm",
    "/whitepaper/ru.htm",
    "/whitepaper/th.htm",
    "/whitepaper/uk.htm",
    "/whitepaper/vi.htm",
    "/whitepaper/zh-CN.htm",
    "/whitepaper/zh-TW.htm"
  ]
};

// node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Users/user/Documents/workspace/project/delta-web/.wrangler/tmp/pages-mmO7jK/bundledWorker-0.8035856558080374.mjs";
import { isRoutingRuleMatch } from "/Users/user/Documents/workspace/project/delta-web/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Users/user/Documents/workspace/project/delta-web/.wrangler/tmp/pages-mmO7jK/bundledWorker-0.8035856558080374.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        if (worker.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return worker.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=pfmmyh01mx.js.map
